module Corgibytes
  module Freshli
    module Commons
      # The actual version number is generated by the git-version-bump gem
      # before the gem is built.
      VERSION = "0.0.0"
    end
  end
end
